/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package edunova.zavrsnirad.view;

import edunova.zavrsnirad.controller.ObradaEvidencija;
import edunova.zavrsnirad.model.Evidencija;
import java.awt.event.KeyEvent;
import java.math.BigDecimal;
import java.math.RoundingMode;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/**
 *
 * @author srdja
 */
public class RadSEvidencijomForma extends javax.swing.JFrame {

    private ObradaEvidencija obrada;
    
    public RadSEvidencijomForma() {
        initComponents();
        setTitle(Aplikacija.NASLOV_APP + " - Rad s evidencijom");
        obrada = new ObradaEvidencija();
        ucitaj();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        lstEvidencije = new javax.swing.JList<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtCijenaGoriva = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtNatocenoLitara = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtPocetnoStanje = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtZavrsnoStanje = new javax.swing.JTextField();
        txtAuto = new javax.swing.JTextField();
        txtDatum = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtUkupnaCijena = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtUdaljenost = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtPotGorivaPoKm = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtPotKunaPoKm = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel11 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        lstEvidencije.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                lstEvidencijeValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(lstEvidencije);

        jLabel1.setText("Datum:");

        jLabel3.setText("Auto:");

        jLabel5.setText("Cijena goriva po litri (kn):");

        txtCijenaGoriva.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtCijenaGorivaKeyReleased(evt);
            }
        });

        jLabel4.setText("Natočeno litara:");

        txtNatocenoLitara.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtNatocenoLitaraKeyReleased(evt);
            }
        });

        jLabel6.setText("Početno stanje brojila:");

        txtPocetnoStanje.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtPocetnoStanjeKeyReleased(evt);
            }
        });

        jLabel7.setText("Završno stanje brojila:");

        txtZavrsnoStanje.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtZavrsnoStanjeKeyReleased(evt);
            }
        });

        jLabel2.setText("Ukupna cijena goriva (kn):");

        jLabel8.setText("Prijeđena udaljenost (km):");

        jLabel9.setText("Potrošnja goriva (L/100km):");

        jLabel10.setText("Potrošeni iznos u kunama (kn/100km):");

        jLabel11.setText("Odaberite evidenciju:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtPocetnoStanje)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtNatocenoLitara)
                                    .addComponent(txtCijenaGoriva, javax.swing.GroupLayout.DEFAULT_SIZE, 229, Short.MAX_VALUE)
                                    .addComponent(jLabel3)
                                    .addComponent(txtAuto)
                                    .addComponent(txtDatum)
                                    .addComponent(txtZavrsnoStanje))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 103, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtUkupnaCijena)
                                    .addComponent(txtUdaljenost)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, 171, Short.MAX_VALUE)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(74, 74, 74))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtPotGorivaPoKm)
                                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtPotKunaPoKm, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jSeparator3, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jSeparator2, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jSeparator1))
                                .addContainerGap())))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(10, 10, 10)
                        .addComponent(txtDatum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtAuto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtCijenaGoriva, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtNatocenoLitara, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtUkupnaCijena, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtPocetnoStanje, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtZavrsnoStanje, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtUdaljenost, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel9)
                        .addGap(16, 16, 16)
                        .addComponent(txtPotGorivaPoKm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtPotKunaPoKm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 536, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(26, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void lstEvidencijeValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_lstEvidencijeValueChanged
        if(evt.getValueIsAdjusting()){
            return;
        }
        
        if(lstEvidencije.getSelectedValue() == null){
            return;
        }
        
        obrada.setEntitet(lstEvidencije.getSelectedValue());
        
        var e = obrada.getEntitet();

        
        txtDatum.setText(e.getDatum().toString());
        txtAuto.setText(e.getAuto().toString());
        txtCijenaGoriva.setText(e.getCijenaGorivaPoLitri().setScale(2, RoundingMode.HALF_UP).toString());       
        txtNatocenoLitara.setText(e.getNatocenoLitara().setScale(2, RoundingMode.HALF_UP).toString());
        txtPocetnoStanje.setText(String.valueOf(e.getPocetnoStanje()));
        txtZavrsnoStanje.setText(String.valueOf(e.getZavrsnoStanje()));
        
        txtUkupnaCijena.setText(e.getCijenaGorivaPoLitri().multiply(e.getNatocenoLitara())
            .setScale(2, RoundingMode.HALF_UP).toString());
        
        txtUdaljenost.setText(String.valueOf(e.getZavrsnoStanje()-e.getPocetnoStanje()));
        
        txtPotGorivaPoKm.setText((e.getNatocenoLitara()
            .divide((BigDecimal.valueOf(e.getZavrsnoStanje()))
                .subtract(BigDecimal.valueOf(e.getPocetnoStanje())),2,RoundingMode.HALF_UP))
        .multiply(new BigDecimal(100))
        .toString());
        
        txtPotKunaPoKm.setText((e.getCijenaGorivaPoLitri().multiply(e.getNatocenoLitara())
            .setScale(2, RoundingMode.HALF_UP)
            .divide((BigDecimal.valueOf(e.getZavrsnoStanje()))
                .subtract(BigDecimal.valueOf(e.getPocetnoStanje())),2,RoundingMode.HALF_UP))
        .multiply(new BigDecimal(100))
        .toString());
    }//GEN-LAST:event_lstEvidencijeValueChanged

    private void txtCijenaGorivaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCijenaGorivaKeyReleased
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            izracunCijeneGoriva();
            izracuni();
        }
    }//GEN-LAST:event_txtCijenaGorivaKeyReleased

    private void txtNatocenoLitaraKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNatocenoLitaraKeyReleased
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            izracunCijeneGoriva();
            izracuni();
        }
    }//GEN-LAST:event_txtNatocenoLitaraKeyReleased

    private void txtPocetnoStanjeKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPocetnoStanjeKeyReleased
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            izracuni();
        }
    }//GEN-LAST:event_txtPocetnoStanjeKeyReleased

    private void txtZavrsnoStanjeKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtZavrsnoStanjeKeyReleased
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            izracuni();
        }
    }//GEN-LAST:event_txtZavrsnoStanjeKeyReleased

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JList<Evidencija> lstEvidencije;
    private javax.swing.JTextField txtAuto;
    private javax.swing.JTextField txtCijenaGoriva;
    private javax.swing.JTextField txtDatum;
    private javax.swing.JTextField txtNatocenoLitara;
    private javax.swing.JTextField txtPocetnoStanje;
    private javax.swing.JTextField txtPotGorivaPoKm;
    private javax.swing.JTextField txtPotKunaPoKm;
    private javax.swing.JTextField txtUdaljenost;
    private javax.swing.JTextField txtUkupnaCijena;
    private javax.swing.JTextField txtZavrsnoStanje;
    // End of variables declaration//GEN-END:variables

    private void ucitaj() {
        DefaultListModel<Evidencija> m = new DefaultListModel<>();

        m.addAll(obrada.getPodaci());

        lstEvidencije.setModel(m);
    }

    private void izracunCijeneGoriva() {
        BigDecimal cijena = new BigDecimal(txtCijenaGoriva.getText());
        BigDecimal natoceno = new BigDecimal(txtNatocenoLitara.getText());
        
        if(cijena.compareTo(BigDecimal.ZERO) >= 0 && natoceno.compareTo(BigDecimal.ZERO) >= 0){
            txtUkupnaCijena.setText(cijena.multiply(natoceno)
                                    .setScale(2, RoundingMode.HALF_UP)
                                    .toString());
        }else{
            JOptionPane.showMessageDialog(rootPane, "Cijena goriva i natočeno litara ne smiju biti negativni");
        }
    }

    private void izracuni() {
        BigDecimal ukupna = new BigDecimal(txtUkupnaCijena.getText());
        BigDecimal natoceno = new BigDecimal(txtNatocenoLitara.getText());
        BigDecimal pocetno = new BigDecimal(txtPocetnoStanje.getText());
        BigDecimal zavrsno = new BigDecimal(txtZavrsnoStanje.getText());
        
        if((zavrsno.subtract(pocetno)).compareTo(BigDecimal.ZERO) > 0
                && pocetno.compareTo(BigDecimal.ZERO) > 0){
            txtUdaljenost.setText(zavrsno.subtract(pocetno).toString());
            
            if(natoceno.compareTo(BigDecimal.ZERO) >= 0){
                txtPotGorivaPoKm.setText(natoceno.divide(zavrsno.subtract(pocetno),2,RoundingMode.HALF_UP)
                                    .multiply(new BigDecimal(100))
                                    .toString());
            }else{
                txtPotGorivaPoKm.setText("[greška]");
            }
            
            txtPotKunaPoKm.setText(ukupna.divide(zavrsno.subtract(pocetno),2,RoundingMode.HALF_UP)
                                .multiply(new BigDecimal(100))
                                .toString());
        }else{
            JOptionPane.showMessageDialog(rootPane, "Završno stanje ne smije biti manje ili jednako od početnog stanja "
                    + "i stanja ne smiju biti manja od 0");
        }
        
    }
}
